### ISSUE TITLE
Fatal error while initialising

### ISSUE THREAD

**Issue by Romromius** [ClearwaterUK/UltrakULL#21]
Installed BeplnEx and UltrakULL on a raw game, latest version at the moment.
[LogOutput.log](https://github.com/ClearwaterUK/UltrakULL/files/15229704/LogOutput.log)

**Comment by DaZombieKiller** [comment]
Steam allows you to download previous versions of a game, so you can downgrade that way if you wish. There are a number of guides online that describe the steps to do so.

* `download_depot 1229490 1229491 3459349900810795973`: Patch 15b (current)
* `download_depot 1229490 1229491 7046117606944229568`: Patch 15
* `download_depot 1229490 1229491 3469779734723462375`: Patch 14d

**Comment by ClearwaterUK** [comment]
The current version of UltrakULL (1.2.4) is not compatible with the current version of the game (15b)
The mod dev team are working on the next version (1.3.0) which is currently in private testing, and should hopefully release soon.

**Comment by Romromius** [comment]
Yes, seems like it works. Path 14b loaded with errors, path 15 failed to load with same error
